### ISSUE TITLE
Certain E[DMG] solves still hit the 20 min timeout

### ISSUE THREAD

**Issue by wumphlett** [wumphlett/Eclair#14]
Breaking example:

```
cookies:
- name: Rockstar
  resonant:
  - Tropical Rock
  requirements:
  - Cooldown >= 4.5
  - Cooldown <= 6
  - DMG Resist >= 31
  - CRIT% >= 5
  - max: E[DMG]
    ATK: 51.22
modifiers:
  CRIT DMG:
  - source: Moonstone Relic
    value: 26.1
  CRIT%:
  - source: Whistle Treasure
    value: 15
```

It's unclear if this is due to the min required dmg res, tightly bound cooldown, non-context aware E[DMG] upper bound calculation, or some combination thereof.
